spring:
  thymeleaf:
    cache: false  # 캐시 비활성화
    prefix: classpath:/templates/  # 타임리프 템플릿 위치
    suffix: .html  # 타임리프 템플릿 확장자
  devtools:
    livereload:
      enabled: true  # Live Reload 활성화
  datasource:
    url: jdbc:postgresql://localhost:5432/grapes
    username: dior
    password: Dodzjtm17!!
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        globally_quoted_identifiers: true
        temp:
          use_jdbc_metadata_defaults: false
        jdbc:
          time_zone: UTC
    open-in-view: false
