-- public.web_component definition

-- Drop table

-- DROP TABLE public.web_component;

CREATE TABLE public.web_component (
                                      id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                      "content" text NULL,
                                      CONSTRAINT web_component_pkey PRIMARY KEY (id)
);